name: PR - Build, Test, and Analyze with SonarCloud

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js 설치 및 캐싱
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21" # 원하는 Node.js 버전
          cache: npm

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 빌드 실행
      - name: Build application
        run: npm run build

      # 5. 테스트 실행
      - name: Run tests and generate coverage
        run: |
          npm run test -- --coverage
          mkdir -p coverage

      # 6. SonarCloud 분석
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # SonarCloud API 토큰
        with:
          args: >
            -Dsonar.projectKey=devs32
            -Dsonar.organization=Devs32_invu-server
            -Dsonar.sources=./src 
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
